[versions]
guava = "33.4.0-jre"
jackson = "2.18.3"
jakarta-ws-rs = "3.1.0"
jakarta-inject = "2.0.1"
jakarta-annotation = "2.1.1"
jakarta-servlet = "6.0.0"
jakarta-cdi = "4.0.1"
jakarta-interceptor = "2.1.0"
guice = "7.0.0"
spring = "6.2.18"
log4j = "2.26.0"
junit = "5.13.4"
assertj = "3.27.3"
mockito = "5.23.0"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }

jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }

jakarta-ws-rs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "jakarta-ws-rs" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakarta-servlet" }
jakarta-cdi-api = { module = "jakarta.enterprise:jakarta.enterprise.cdi-api", version.ref = "jakarta-cdi" }
jakarta-interceptor-api = { module = "jakarta.interceptor:jakarta.interceptor-api", version.ref = "jakarta-interceptor" }

guice = { module = "com.google.inject:guice", version.ref = "guice" }

spring-webmvc = { module = "org.springframework:spring-webmvc", version.ref = "spring" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring" }

log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[bundles]
jackson = ["jackson-core", "jackson-databind", "jackson-annotations"]
testing = ["junit-jupiter", "assertj"]
testing-mock = ["junit-jupiter", "assertj", "mockito-core", "mockito-junit"]
